// app/perguntas-frequentes/page.tsx
'use client'

import { Accordion, AccordionItem } from "@nextui-org/react";

export default function Home() {
    return (
        <div className="h-5/6 flex justify-evenly items-center px-32 py-4">
            <Accordion selectionMode="multiple">
                <AccordionItem key="1" aria-label="Accordion 1" title="Qual a data limite de entrega do Imposto de renda?">
                    Prazo para declaração do Imposto de Renda em 2023, termina dia 31 de maio.
                </AccordionItem>
                <AccordionItem key="2" aria-label="Accordion 2" title="Qual o prazo para retificações do Imposto de renda?">
                    O prazo para retificar o Imposto de Renda 2023 é de até 5 anos após o último dia do prazo de envio
                    original (que foi 31 de maio de 2023). A retificação deve ser feita em casos de erros ou falta de
                    informações.
                </AccordionItem>
                <AccordionItem key="3" aria-label="Accordion 3" title="Como recuperar a senha do Gov.com?">
                    Acessando o site https://acesso.gov.br, preencha o seu CPF, clique em “esqueci minha senha”, clique em
                    gerar QR-CODE, aponte o celular e leia o QR-CODE, após leitura, faça o reconhecimento facial e redefina
                    sua senha. No site abaixo apresenta mais formas de recuperar a senha. Com opções de e-mail, mensagem de
                    texto – SMS e credencias de banco. https://acesso.gov.br/faq/_perguntasdafaq/formarrecuperarconta.html
                </AccordionItem>
            </Accordion>
        </div>
    )
}

// pages/perguntas-frequentes.vue
<template>
    <div class="h-5/6 flex flex-col justify-center items-center space-y-4">
        <div class="relative w-4/5 rounded-3xl bg-gray-100 drop-shadow-lg">
            <input type="checkbox" class="absolute top-0 inset-x-0 w-full h-10 cursor-pointer z-10 opacity-0 peer">
            <div class="h-10 flex items-center pl-4">
                <h1 class="text-xl">Qual a data limite de entrega do Imposto de renda?</h1>
            </div>
            <div class="absolute top-2 right-3 transition-transform- duration-500 rotate-0 peer-checked:rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
            </div>

            <div class="px-4 overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-20">
                <h1>
                    Prazo para declaração do Imposto de Renda em 2023, termina dia 31 de maio.
                </h1>
            </div>
        </div>

        <div class="relative w-4/5 rounded-3xl bg-gray-100 drop-shadow-lg">
            <input type="checkbox" class="absolute top-0 inset-x-0 w-full h-10 cursor-pointer z-10 opacity-0 peer">
            <div class="h-10 flex items-center pl-4">
                <h1 class="text-xl">Qual o prazo para retificações do Imposto de renda?</h1>
            </div>
            <div class="absolute top-2 right-3 transition-transform- duration-500 rotate-0 peer-checked:rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
            </div>

            <div class="px-4 overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-20">
                <h1>
                    O prazo para retificar o Imposto de Renda 2023 é de até 5 anos após o último dia do prazo de envio
                    original (que foi 31 de maio de 2023). A retificação deve ser feita em casos de erros ou falta de
                    informações.
                </h1>
            </div>
        </div>

        <div class="relative w-4/5 rounded-3xl bg-gray-100 drop-shadow-lg">
            <input type="checkbox" class="absolute top-0 inset-x-0 w-full h-10 cursor-pointer z-10 opacity-0 peer">
            <div class="h-10 flex items-center pl-4">
                <h1 class="text-xl">Como recuperar a senha do Gov.com?</h1>
            </div>
            <div class="absolute top-2 right-3 transition-transform- duration-500 rotate-0 peer-checked:rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
            </div>

            <div class="px-4 overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-20">
                <h1>
                    Acessando o site https://acesso.gov.br, preencha o seu CPF, clique em “esqueci minha senha”, clique em
                    gerar QR-CODE, aponte o celular e leia o QR-CODE, após leitura, faça o reconhecimento facial e redefina
                    sua senha. No site abaixo apresenta mais formas de recuperar a senha. Com opções de e-mail, mensagem de
                    texto – SMS e credencias de banco. https://acesso.gov.br/faq/_perguntasdafaq/formarrecuperarconta.html
                </h1>
            </div>
        </div>

        <div class="relative w-4/5 rounded-3xl bg-gray-100 drop-shadow-lg">
            <input type="checkbox" class="absolute top-0 inset-x-0 w-full h-10 cursor-pointer z-10 opacity-0 peer">
            <div class="h-10 flex items-center pl-4">
                <h1 class="text-xl">Como recuperar a senha do Gov.com?</h1>
            </div>
            <div class="absolute top-2 right-3 transition-transform- duration-500 rotate-0 peer-checked:rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
            </div>

            <div class="px-4 overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-20">
                <h1>
                    Acessando o site https://acesso.gov.br, preencha o seu CPF, clique em “esqueci minha senha”, clique em
                    gerar QR-CODE, aponte o celular e leia o QR-CODE, após leitura, faça o reconhecimento facial e redefina
                    sua senha. No site abaixo apresenta mais formas de recuperar a senha. Com opções de e-mail, mensagem de
                    texto – SMS e credencias de banco. https://acesso.gov.br/faq/_perguntasdafaq/formarrecuperarconta.html
                </h1>
            </div>
        </div>
    </div>
</template>
  
<script>


export default {
    layout: 'default'
}
</script>
